/**
 * Human-reviewed translations for CMS / API English phrases.
 * Used before Google Translate to avoid wrong or inconsistent meanings.
 */
const PHRASES: Record<string, Record<string, string>> = {
  nl: {
    "Spring Deals": "Voorjaarsaanbiedingen",
    "Spring deals": "Voorjaarsaanbiedingen",
    "Shop now": "Nu shoppen",
    "Shop Now": "Nu shoppen",
    "Up to 50% off": "Tot 50% korting",
    "Up to 50% Off": "Tot 50% korting",
    "Bestsellers": "Best verkocht",
    "Best sellers": "Best verkocht",
    "Deals": "Aanbiedingen",
    "Clearance": "Opruiming",
    "Outlet": "Outlet",
    "Relief": "Verlichting",
    "Buying lighting? Choose a category": "Verlichting kopen? Kies een categorie",
    "View all": "Alles bekijken",
    "View All": "Alles bekijken",
    "Learn more": "Meer informatie",
    "Read more": "Lees meer",
    "Add to cart": "In winkelwagen",
    "Free shipping on orders over €75": "Gratis verzending vanaf €75",
    "Secure checkout": "Veilig afrekenen",
    "New arrivals": "Nieuw binnen",
    "Featured": "Uitgelicht",
    "Sale": "Sale",
    "Interior lighting": "Binnenverlichting",
    "Outdoor lighting": "Buitenverlichting",
    "Light sources": "Lichtbronnen",
    "Categories": "Categorieën",
    "Pendant lights": "Hanglampen",
    "Ceiling lights": "Plafondlampen",
    "Wall lights": "Wandlampen",
    "Table lamps": "Tafellampen",
    "Floor lamps": "Vloerlampen",
    "Rooms": "Ruimtes",
    "Living room": "Woonkamer",
    "Bedroom": "Slaapkamer",
    "Kitchen": "Keuken",
    "Bathroom": "Badkamer",
    "Dining room": "Eetkamer",
    "Hallway": "Hal",
    "Styles": "Stijlen",
    "Modern": "Modern",
    "Industrial": "Industrieel",
    "Classic": "Klassiek",
    "Vintage": "Vintage",
    "Design": "Design",
    "Rustic": "Rustiek",
    "Smart lighting": "Slimme verlichting",
    "LED strips": "LED strips",
    "Outdoor wall lights": "Buiten wandlampen",
    "Standing lights": "Staande lampen",
    "Solar lights": "Solarlampen",
    "Sensor lights": "Sensorlampen",
    "Spotlights": "Spots",
    "Motion sensor": "Bewegingssensor",
    "Dimmable": "Dimbaar",
    "Smart outdoor": "Slimme buitenverlichting",
    "New in": "Nieuw binnen",
    "Offers": "Aanbiedingen",
    "Shop Deals": "Shop Aanbiedingen",
    "Pendant Deals": "Hanglamp Aanbiedingen",
    "Wall Light Deals": "Wandlamp Aanbiedingen",
    "Floor Lamp Deals": "Vloerlamp Aanbiedingen",
    "Table Lamp Deals": "Tafellamp Aanbiedingen",
    "Bulb Deals": "Lichtbron Aanbiedingen",
    "Discount Type": "Soort Korting",
    "Under €250": "Onder €250",
    "Under €50": "Onder €50",
    "Bundle Offers": "Bundelaanbiedingen",
    "Bestsellers on Sale": "Bestverkocht in de Sale",
    "Limited Time Offers": "Tijdelijke Aanbiedingen",
    "New Deals": "Nieuwe Aanbiedingen",
    "Fittings": "Fittingen",
    "E27 (Large)": "E27 (Groot)",
    "E14 (Small)": "E14 (Klein)",
    "GU10": "GU10",
    "G9": "G9",
    "Types": "Soorten",
    "LED Bulbs": "LED lampen",
    "Smart Bulbs": "Slimme lampen",
    "Filament Bulbs": "Filament lampen",
    "Business lighting": "Zakelijke verlichting",
    "Smart home": "Smart home",
    "Accessories": "Accessoires",
    "Pendant lamps": "Hanglampen",
    "Ceiling lamps": "Plafondlampen",
    "Wall lamps": "Wandlampen",
    "Floor lamps": "Vloerlampen",
    "Table lamps": "Tafellampen",
    "Chandeliers": "Kroonluchters",
    "Outdoor lamps": "Buitenlampen",
    "String lights": "Lichtslingers",
    "LED bulbs": "LED lampen",
    "Smart bulbs": "Slimme lampen",
    "Office lighting": "Kantoorverlichting",
    "Lampshades": "Lampenkappen",
    "15,000+ reviews": "15.000+ reviews",
    "Ordered before 22:00, delivered next day": "Voor 22:00 besteld, morgen in huis",
    "30-day returns": "30 dagen bedenktijd",
    "Business": "Zakelijk",
    "Customer service": "Klantenservice",
    "Contact us": "Neem contact op",
    "About us": "Over ons",
    "Our story": "Ons verhaal",
    "(View styles & all options)": "(Bekijk stijlen & alle opties)",
    "Larger quantity required?": "Grotere hoeveelheid nodig?",
    "Request a quote": "Vraag een offerte aan",
    "Buy now, pay later with Klarna": "Koop nu, betaal later met Klarna",
    "Do you have a question about this product?": "Heeft u een vraag over dit product?",
    "Our employee is happy to help you find the right product": "Onze medewerker helpt u graag bij het vinden van het juiste product",
    "Send mail": "Stuur een e-mail",
    "Free shipping over €100 in NL": "Gratis verzenden boven €100,- in NL",
    "Free shipping above €100 in NL": "Gratis verzenden boven €100,- in NL",
    "Physical store": "Fysieke winkel",
    "Order today, pick up in store today": "Vandaag bestellen vandaag afhalen in de winkel",
    "Ordered before 15:00, shipped today": "Voor 15:00 besteld vandaag verzonden",
  },
};

// CMS often stores Dutch copy — map back to English when TAAL is EN.
const NL_TO_EN: Record<string, string> = {};
for (const [english, dutch] of Object.entries(PHRASES.nl)) {
  NL_TO_EN[dutch] = english;
  NL_TO_EN[english] = english;
}
// Common Dutch header variants (CMS / topbar)
Object.assign(NL_TO_EN, {
  "15.000+ reviews": "15,000+ reviews",
  "15,000+ beoordelingen": "15,000+ reviews",
  "15.000+ beoordelingen": "15,000+ reviews",
  "30 dagen retourrecht": "30-day returns",
  "Bestel voor 22:00, morgen in huis": "Order before 22:00, delivered next day",
  "Voor 22:00 besteld, morgen in huis": "Ordered before 22:00, delivered next day",
  "30 dagen retour": "30-day returns",
  "30 dagen bedenktijd": "30-day returns",
  Zakelijke: "Business",
  Klantenservice: "Customer service",
  KLANTENSERVICE: "Customer service",
  Winkel: "Shop",
  WINKEL: "Shop",
  "Over Schip & ster": "About Schip & ster",
  "OVER SCHIP & STER": "About Schip & ster",
  "Verzending & levering": "Shipping & delivery",
  Retourneren: "Returns",
  Betaalmethoden: "Payment methods",
  Garantie: "Warranty",
  "Algemene Voorwaarden": "Terms & Conditions",
  Terugbetalingsbeleid: "Refund policy",
  Duurzaamheid: "Sustainability",
  Vacatures: "Careers",
  Pers: "Press",
  "Gratis verzending boven €75": "Free shipping over €75",
  "Gratis verzending vanaf €75": "Free shipping over €75",
  "Veilig afrekenen": "Secure checkout",
  "iDEAL · Card · PayPal": "iDEAL · Card · PayPal",
  "Schip & ster — verlicht jouw moment. Onze klantenservice is dagelijks bereikbaar via e-mail of telefoon. Wij voeren meer dan 10.000 verlichtingsproducten met snelle verzending en 30 dagen retour.":
    "Schip & ster — light up your moment. Our customer service is available daily by email or phone. We carry more than 10,000 lighting products with fast shipping and 30-day returns.",
  "Schip & ster — verlicht jouw moment. Onze klantenservice is dagelijks bereikbaar via e-mail of telefoon.":
    "Schip & ster — light up your moment. Our customer service is available daily by email or phone.",
  Contact: "Contact",
  FAQ: "FAQ",
  Privacy: "Privacy",
  Showroom: "Showroom",
  Blog: "Blog",
  "Ons verhaal": "Our story",
  Binnenverlichting: "Indoor lighting",
  Buitenverlichting: "Outdoor lighting",
  "Zakelijke verlichting": "Business lighting",
  Aanbiedingen: "Deals",
  Lichtbronnen: "Light sources",
  Groothandel: "Wholesale",
  Samenwerkingen: "Partnerships",
  "Zakelijke verlichting voor grotere inkoopvolumes":
    "Business lighting for larger purchase volumes",
  "Voor retailers, aannemers, architecten, interieurprofessionals en projectinkopers die zoeken naar scherpe prijzen, betrouwbare levering en persoonlijke ondersteuning.":
    "For retailers, contractors, architects, interior professionals and project buyers looking for competitive prices, reliable delivery and personal support.",
  "Vraag een offerte aan": "Request a quote",
  "Bekijk de voordelen": "View the benefits",
  Bulk: "Bulk",
  Zakelijk: "Business",
  Project: "Project",
  "Ondersteuning bij grotere bestellingen": "Support for larger orders",
  "Scherpe prijzen voor professionals": "Competitive prices for professionals",
  "Passend advies voor zakelijke inkoop": "Tailored advice for business purchasing",

  // Product specification labels (Dutch → English)
  "Aantal lichten": "Number of lights",
  "IP-rating": "IP Rating",
  "IP rating": "IP Rating",
  "Materiaal": "Material",
  "Stijl": "Style",
  "Kleur": "Colour",
  "Kleur/Afwerking": "Colour / Finish",
  "Hoogte in cm": "Height in cm",
  "Breedte in cm": "Width in cm",
  "Lengte in cm": "Length in cm",
  "Diameter in cm": "Diameter in cm",
  "Diameter": "Diameter",
  "Hoogte voet/montageplaat": "Height of foot/mounting plate",
  "Voet/montageplaat lengte": "Foot/mounting plate length",
  "Basis/montageplaat breedte in cm": "Base/mounting plate width in cm",
  "Aansluitspanning": "Connection voltage",
  "Maximaal vermogen": "Maximum wattage",
  "Type fitting": "Type of fitting",
  "Fitting": "Bulb fitting",
  "Inclusief lamp": "Includes light",
  "Dimbaar": "Dimmable",
  "Garantie": "Warranty",
  "Artikelnummer": "Article number",
  "Installatiehandleiding": "Installation Manual",
  "Reeks": "Series",
  "Ja (niet inbegrepen)": "Yes (not included)",
  "Ja": "Yes",
  "Nee": "No",
  "Ruimte": "Room",
  "Kleur temperatuur": "Colour temperature",
  "Lichtkleur": "Light colour",
  "Lumen": "Lumen",
  "Wattage": "Wattage",
  "Energielabel": "Energy label",
  "Spanning": "Voltage",
  "Beschermingsgraad": "Protection class",
  "Ophangmethode": "Hanging method",
  "Montage": "Mounting",
  "Gewicht": "Weight",
  "Merk": "Brand",
  "Collectie": "Collection",
  "Kleur correlated temperatuur": "Colour correlated temperature",
  "Snoerlengte": "Cable length",
  "Snoer": "Cable",
  "Inbouw": "Recessed",
  "Opbouw": "Surface mounted",
  "Pendel": "Pendant",
  "Reflector": "Reflector",
  "Lichthoek": "Light angle",
  "CRI": "CRI",

  // English spec labels that sometimes pass through (identity map)
  "Number of lights": "Number of lights",
  "IP Rating": "IP Rating",
  "Material": "Material",
  "Style": "Style",
  "Colour": "Colour",
  "Color": "Color",
  "Height in cm": "Height in cm",
  "Width in cm": "Width in cm",
  "Length in cm": "Length in cm",
  "Diameter": "Diameter",
  "Connection voltage": "Connection voltage",
  "Maximum wattage": "Maximum wattage",
  "Type of fitting": "Type of fitting",
  "Bulb fitting": "Bulb fitting",
  "Includes light": "Includes light",
  "Dimmable": "Dimmable",
  "Warranty": "Warranty",
  "Article number": "Article number",
  "Installation Manual": "Installation Manual",
  "Series": "Series",
  "Yes (not included)": "Yes (not included)",
  "Room": "Room",
  "Height of foot/mounting plate": "Height of foot/mounting plate",
  "Foot/mounting plate length": "Foot/mounting plate length",
  "Base/mounting plate width in cm": "Base/mounting plate width in cm",
});

PHRASES.en = NL_TO_EN;

/** Look up a curated translation; case-insensitive fallback. */
export function lookupStaticPhrase(text: string, targetLang: string): string | null {
  if (!text?.trim()) return null;
  const lang = targetLang.split("-")[0].toLowerCase();

  const table = PHRASES[lang];
  if (!table) return null;

  const trimmed = text.trim();
  if (table[trimmed]) return table[trimmed];

  const lower = trimmed.toLowerCase();
  for (const [key, value] of Object.entries(table)) {
    if (key.toLowerCase() === lower) return value;
  }
  return null;
}
