export const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";
export const API_PREFIX = "/api/v1";

export const ENDPOINTS = {
  PRODUCTS: `${BASE_URL}${API_PREFIX}/products`,
  CATEGORIES: `${BASE_URL}${API_PREFIX}/categories`,
  BRANDS: `${BASE_URL}${API_PREFIX}/brands`,
  SERIES: `${BASE_URL}${API_PREFIX}/series`,
  ATTRIBUTES: `${BASE_URL}${API_PREFIX}/attributes`,
  MEGAMENUS: `${BASE_URL}${API_PREFIX}/megamenus`,
  CMS_HOMEPAGE: `${BASE_URL}${API_PREFIX}/cms/homepage`,
  CMS_RELIEF: `${BASE_URL}${API_PREFIX}/cms/relief`,
  CMS_PAGES: `${BASE_URL}${API_PREFIX}/cms/pages`,
  CMS_PAGE: `${BASE_URL}${API_PREFIX}/cms`,
  MEDIA: `${BASE_URL}${API_PREFIX}/media`,
  AUTH: `${BASE_URL}${API_PREFIX}/auth`,
  BLOGS: `${BASE_URL}${API_PREFIX}/blogs`,
  REVIEWS: `${BASE_URL}${API_PREFIX}/reviews`,
  CMS_FEATURES: `${BASE_URL}${API_PREFIX}/cms/features`,
  ADDRESSES: `${BASE_URL}${API_PREFIX}/addresses`,
  ADMIN_SETTINGS: `${BASE_URL}${API_PREFIX}/admin/settings`,
  EMAIL_TEMPLATES: `${BASE_URL}${API_PREFIX}/admin/email-templates`,
  WISHLIST: `${BASE_URL}${API_PREFIX}/wishlists`,
  COUPONS: `${BASE_URL}${API_PREFIX}/coupons`,
  CHARGES: `${BASE_URL}${API_PREFIX}/charges`,
  ORDERS: `${BASE_URL}${API_PREFIX}/orders`,
  SEO_ROBOTS: `${BASE_URL}${API_PREFIX}/admin/settings/seo/robots`,
  SEO_SITEMAP: `${BASE_URL}${API_PREFIX}/admin/settings/seo/sitemap`,
  ADMIN_SEO_CONFIG: `${BASE_URL}${API_PREFIX}/admin/settings/seo/config`,
  PUBLIC_SEO_CONFIG: `${BASE_URL}${API_PREFIX}/cms/seo-config`,
  ADMIN_ANALYTICS_DATA: `${BASE_URL}${API_PREFIX}/admin/settings/analytics/data`,
};
